package mobiotics.lco.testCases;

import java.io.File;
import java.io.IOException;
//import java.util.concurrent.TimeUnit;
import java.util.List;

import org.apache.commons.io.FileUtils;
import org.apache.commons.lang3.RandomStringUtils;
import org.apache.log4j.Logger;
import org.apache.log4j.PropertyConfigurator;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.OutputType;
import org.openqa.selenium.TakesScreenshot;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Parameters;

import com.aventstack.extentreports.ExtentReports;
import com.aventstack.extentreports.ExtentTest;

import mobiotics.lco.pageObjects.ActivateBasePackPage;
import mobiotics.lco.pageObjects.Add_Indigital_Pay_Bouquet;
import mobiotics.lco.pageObjects.SubscribePage;
import mobiotics.lco.utilities.DemoExcelLibrary3;
import mobiotics.lco.utilities.EnterCanDetails;
import mobiotics.lco.utilities.ReadConfig;


public class BaseClass {
	
	ReadConfig readconfig= new ReadConfig();
	public String baseURL=readconfig.getApplicationURL();
	
	public String FrCode=readconfig.getFrCode();
	
	public String password=readconfig.getPassword();
	public static WebDriver driver;
	public static Logger logger;
	
	public Add_Indigital_Pay_Bouquet addindigi;
	public ActivateBasePackPage activateBasePack;
	
	EnterCanDetails enterCanDetails;
	
	
	public SubscribePage sp;
	
	@Parameters("browser")
	
	
	@BeforeClass
	public void setUp(String br) {
		
		
		
		
		logger=logger.getLogger("LOC_ Logger");
		PropertyConfigurator.configure("Log4j.properties");
		
		addindigi=new Add_Indigital_Pay_Bouquet(driver);
		
		activateBasePack= new ActivateBasePackPage(driver);
		
		sp=new SubscribePage(driver);
		
		enterCanDetails=new EnterCanDetails(addindigi, activateBasePack, driver,logger);
		
		
	/*
		
		if(br.equals("chrome")) {
			System.setProperty("webdriver.chrome.driver", readconfig.getChromePath());
			driver= new ChromeDriver();
			
		}
		
		else if(br.equals("firefox")) {
			System.setProperty("webdriver.gecko.driver", readconfig.getFirefoxPath());
			driver= new FirefoxDriver();
			
		}
		
		else if(br.equals("ie")) {
			System.setProperty("webdriver.ie.driver", readconfig.getIEPath());
			driver= new InternetExplorerDriver();
			
		}
		
		
		driver.manage().window().maximize();
		driver.get(baseURL);
		driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
		*/
	}
	
	

	public void captureScreen(WebDriver driver, String tname) throws IOException {
		TakesScreenshot ts = (TakesScreenshot) driver;
		File source = ts.getScreenshotAs(OutputType.FILE);
		File target = new File(System.getProperty("user.dir") + "/Screenshots/" + tname + ".png");
		FileUtils.copyFile(source, target);
		System.out.println("Screenshot taken");
	}
	
	public String setRandomstring() {
		String autogeneratedstrString=RandomStringUtils.randomAlphabetic(6);
		return autogeneratedstrString;
	}
	
	public void scrollScript() {
		JavascriptExecutor js= (JavascriptExecutor)driver;
		js.executeScript("window.scroll(0,1000)");
		
	}
	
	public void clickRadioButton() {
		
		 List<WebElement> allRadio=driver.findElements(By.xpath("//input[@type='checkbox']"));
		    int size=allRadio.size();
		    
		    
		    for (int i = 0; i < size; i++) {
		    	WebElement radioButton=allRadio.get(i);
				if(radioButton.isEnabled()==true) {
					radioButton.click();
				}
				
			}
		    
	}
	
	  public String enterCanDetails1() {
			String path=System.getProperty("user.dir")+"/src/test/java/mobiotics/lco/testData/TestData.xlsx";
			String canNumber=DemoExcelLibrary3.getexcelData("can.stb.smc", 1, 0, path);
			System.out.println(canNumber);
              sp.enterCanNumber(canNumber);
			//activateBasePack.enterCanNumber(canNumber);
			logger.info("user entered "+canNumber+" for activate in degital pay Bouquet");
			
			activateBasePack.clickGoButton();
			
			System.out.println("can details has been entered");
			
			return canNumber;
		}	
}